/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/dog.glb");
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    // Play the Idle1 animation
    if (actions.Idle1) {
      actions.Idle1.play();
    }
  }, [actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="Circle"
          castShadow
          receiveShadow
          geometry={nodes.Circle.geometry}
          material={materials.Eyes}
          position={[0, 1.382, 0.345]}
          rotation={[0.308, 0, 0]}
          scale={[0.426, 0.309, 0.309]}
        />
        <mesh
          name="Circle001"
          castShadow
          receiveShadow
          geometry={nodes.Circle001.geometry}
          material={materials.Eyes}
          position={[0, 0.745, -0.222]}
          rotation={[0.998, 0, 0]}
          scale={[0.426, 0.309, 0.309]}
        />
        <group name="Dog">
          <group name="DogMesh">
            <skinnedMesh
              name="Cube001"
              geometry={nodes.Cube001.geometry}
              material={materials.Base}
              skeleton={nodes.Cube001.skeleton}
            />
            <skinnedMesh
              name="Cube001_1"
              geometry={nodes.Cube001_1.geometry}
              material={materials.Eyes}
              skeleton={nodes.Cube001_1.skeleton}
            />
          </group>
          <primitive object={nodes.spine004} />
        </group>
        <mesh
          name="JacketMesh001"
          castShadow
          receiveShadow
          geometry={nodes.JacketMesh001.geometry}
          material={materials.Lifejacket}
          position={[0, 1.425, -0.293]}
          rotation={[2.438, 0, Math.PI]}
          scale={0.725}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/dog.glb");
